.circleci/config.yml
package.json
src/commands/deploy/functions.ts
src/commands/env/create/compute.ts
src/commands/env/delete.ts
src/commands/env/log/tail.ts
src/commands/env/var/get.ts
src/commands/generate/function.ts
src/commands/run/function.ts
src/commands/run/function/start.ts
src/hooks/deploy.ts
src/lib/api-client.ts
src/lib/base.ts
src/lib/git.ts
src/lib/project-toml.ts
test/helpers/vacuum.ts
test/lib/redactor.test.ts
yarn.lock

Resolves failing `test-ts-update` tests
@W-10190107@

chore: resolve test-ts-update failures

---

package.json

chore(cli): version bump to 1.2.2

---

package.json
src/commands/login/functions.ts

Uses jsforce for login rather than axios. Hoping this solves bouygues telecom's DNS issue.
@W-10203652@

feat(cli): use jsforce for login

---

LICENSE.txt
package.json
yarn.lock

Updates @heroku/functions-core to 0.2.2. It mostly changes dependencies for running local functions. More details here: https://github.com/forcedotcom/sf-fx-runtime-nodejs/pull/266.
@W-10379120@

chore(deps): update @heroku/functions-core

---

src/commands/env/create/compute.ts
src/commands/env/logdrain/add.ts
src/commands/env/logdrain/list.ts
src/commands/env/logdrain/remove.ts
src/commands/login/functions.ts
src/commands/login/functions/jwt.ts
src/lib/api-client.ts

Removes axios in favor of jsforce to ensure compatibility with customer VPNs
@W-10203652@

switch from axios to jsforce

---

src/lib/api-client.ts

fix(cli): add content type header to requests

---

src/lib/base.ts

Changes the base class to inherit from SfCommand.
This moves the plugin further into SF CLI UX compliance and sets up forthcoming --json PRs.

feat: use @saleforce/sf-plugin-core base class SfCommand

---

command-snapshot.json
messages/env.log.md
src/commands/env/log.ts
src/commands/env/log/tail.ts
src/lib/log-stream-utils.ts
test/commands/env/log.test.ts

[GUS Card](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000007YUIzYAO/view)
@W-9904589@

feat: create sf env log command

---

command-snapshot.json
src/commands/run/function.ts
test/commands/run/function.test.ts

Add --json flag sf run function json
@W-10241317@

feat: add json flag to sf run function

---

command-snapshot.json
src/commands/env/delete.ts
test/commands/env/delete.test.ts

Add --json flag support to env delete 
@W-10241238@

feat: add --json to env delete

---

package.json
src/commands/run/function/start.ts
src/commands/run/function/start/local.ts
test/commands/run/function/start.test.ts
test/commands/run/function/start/local.test.ts
yarn.lock

Bumps the version of @heroku/functions-core to 0.3.1 and updates the local functions runner to be compatible with library changes.
https://github.com/heroku/sf-functions-core/pull/45, [@W-10819415@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000sOC4iYAG/view)

fix: update local runner for sf functions

---

src/commands/env/log.ts

Marks the `env log` command as beta.
N/A [[skip-validate-pr]]
Will unblock https://github.com/salesforcecli/cli/pull/240.

chore: mark the env log command as beta

---

command-snapshot.json
src/commands/env/create/compute.ts
test/commands/env/create/compute.test.ts

Add --json flag to sf env create compute
[@W-10179334@](https://gus.lightning.force.com/lightning/r/a07EE00000PNFHlYAP/view) | [@W-9909299@](https://gus.lightning.force.com/lightning/r/a07EE000007opPxYAI/view) | [@W-10922936@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000tx72xYAA/view)

feat: add json flag to env create compute

---

command-snapshot.json
src/commands/deploy/functions.ts
test/commands/project/deploy/functions.test.ts

Add --json flag to `sf deploy functions`
Better error handling
[@W-9909221@](https://gus.lightning.force.com/lightning/r/a07EE000007oTkZYAU/view) | [@W-10241256@](https://gus.lightning.force.com/lightning/r/a07EE00000U0N0AYAV/view)

feat: add json flag to sf deploy functions

---

package.json

Adds a "delete" topic description to package.json.  This in turn fixes the bug in generating the CLI Reference XML files. 
@W-11241703@

fix: Add description of "delete" topic to package.json

---

src/commands/deploy/functions.ts
src/commands/env/create/compute.ts
src/commands/env/delete.ts
src/commands/env/logdrain/add.ts
src/commands/env/logdrain/list.ts
src/commands/env/logdrain/remove.ts
src/commands/env/var/get.ts
src/commands/env/var/list.ts
src/commands/env/var/set.ts
src/commands/env/var/unset.ts
src/commands/generate/function.ts
src/commands/login/functions/jwt.ts
src/commands/logout/functions.ts
src/commands/run/function.ts
src/commands/run/function/start/container.ts
src/commands/whoami/functions.ts
src/lib/base.ts
src/lib/project-toml.ts
test/commands/login/functions/jwt.test.ts

refactors away from `handleError`
[@W-10019547@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000FZThhYAH/view?ws=%2Flightning%2Fr%2FADM_Epic__c%2Fa3QEE0000001R9R2AU%2Fview)

refactor: this.error handling

---

.circleci/config.yml
bin/promote-dist-tags
package.json

fixes broken package promoting to match current sfdx plugin style
@W-0000000@

ci: fix promote package job

---

README.md

adds missing `feat` conventional commit to release json flag feature work
@W-10019547@

feat: update README and release json flag feature

---

package.json

min supported version of node
@W-00000000@

chore(deps): bump node to >=14.x

---

src/commands/deploy/functions.ts

bubbles up deploy functions auth error
@W-10481157@

fix: bubble up deploy functions auth error

---

src/commands/login/functions/jwt.ts

If the response is not a 200, display more helpful errors
@W-10883923@

fix: handle login functions jwt token request http errors more helpfully

---

package.json

Updates package.json with missing "env compute collaborator" topics.
@W-11489347@

Add missing topics to package.json

---

package.json
yarn.lock

This includes:
* https://github.com/forcedotcom/sf-fx-runtime-nodejs/pull/444
Full changes:
https://github.com/heroku/sf-functions-core/compare/v0.5.0...v0.5.1
[@W-11543508@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000013Cn6xYAC/view)

fix: bump @heroku/functions-core to 0.5.1

---

package.json
yarn.lock

This includes an updated java runtime to address:
* https://github.com/forcedotcom/sf-fx-runtime-java/pull/364
Full changes: https://github.com/heroku/sf-functions-core/compare/v0.5.2...v0.5.3
[@W-12157391@](https://gus.lightning.force.com/a07EE00001FgZMwYAN)

fix: bump @heroku/functions-core to ^0.5.3

---

src/commands/logout/functions.ts
test/commands/logout/functions.test.ts

invalidate session on logout
@W-11548350@
https://salesforce.quip.com/PwMdAsB99jxe

fix: invalidate session on logout

---

package.json
yarn.lock

Bumps @heroku/functions-core from 0.6.0 to 0.7.0
[@W-12514513@](https://gus.lightning.force.com/a07EE00001KunfCYAR)

feat(deps): bump @heroku/functions-core from 0.6.0 to 0.7.0

---

.gitignore
.sfdevrc.json
package.json
yarn.lock

Publish `oclif.lock` to lock deps during plugin install
@W-14071765@

feat: use oclif.lock

---

src/commands/env/create/compute.ts

Fixes release-blocking lint error in #753 
Same ustomer Investigation as #753:
[@W-14371436@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001dByE3YAK/view)

fix(compute): fix linting error
