package.json
Bumps the version to 1.3.1. This should release #337 and #310 which both improve the dockerless experience in minor ways.
@W-10379120@
=> chore: release 1.3.1

package.json, yarn.lock
Update heroku/function-core to 0.2.3 to pick up the release of the new sf-fx-runtime-java v1.0.5
[sf-fx-runtime-java #210](https://github.com/forcedotcom/sf-fx-runtime-java/pull/210)
[W-10397677](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000dGlPhYAK/view)
=> fix: update heroku function-core to 0.2.3

command-snapshot.json, messages/run.function.start.md, src/commands/run/function/start.ts, src/commands/run/function/start/local.ts, test/commands/run/function/start.test.ts
This changes `sf run function start` to behave like `sf run function start local` ("Dockerless"/local mode) instead of behaving like `sf run function start container` (Docker/container mode) as it does today. 
With this PR `sf run function start` behaves identically to `sf run function start local`, with the exception that it still accepts the flags relevant to `sf run function start container`. Those flags (`--builder`, `--network`, `--no-pull`, etc.) are not relevant in local mode, so are accepted, but flagged as deprecated in help and in warning messages.
For more context on why we're doing this and the plan of execution see: https://salesforce.quip.com/CnpKAFNnfZBC
[W-10409382](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07EE00000e18skYAA)
=> feat: run:function:start defaults to local mode

.circleci/config.yml, package.json
Our [latest release](https://circleci.com/gh/salesforcecli/plugin-functions/7146?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) has failed with this error:
This is due to an upstream bug in npm: https://github.com/npm/cli/issues/4234.
According to https://salesforce-internal.slack.com/archives/C01LKDT1P6J/p1642612210084100, this issue does not occur with LTS node releases.
This PR changes the `release-management/test-package` Circle job to use windows/LTS instead of windows/latest, which should allow our release automation to work again. 
This PR also bumps the minor version, since the automation failed on https://github.com/salesforcecli/plugin-functions/commit/a2bd50c950cd9fe4f77bd6e6f3d662a977b9946c. …
=> chore: fix windows package testing

package.json, yarn.lock
Adds support for com.salesforce.salesforce.api-version by updating to the latest version of `@heroku/functions-core`. The latest version includes these changes: https://github.com/heroku/sf-functions-core/pull/37, https://github.com/heroku/sf-functions-core/pull/36. Both target the introduction of `com.salesforce.salesforce-api-version` in a function's `project.toml`. More details can be found in our feature document: https://salesforce.quip.com/auYwAHFJLoNy.
@[W-10679434](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07EE00000n8Y8mYAE)@
@[W-10474584](https://gus.my.salesforce.com/a07EE00000htVsBYAU)@
=> feat: com.salesforce.salesforce-api-version

src/commands/run/function/start.ts
Adds missing help text for the `--language` flag for `sf run function start`
@[W-10466337](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07EE00000h8F1HYAU)@
=> fix: add help text for run function start --language

package.json, yarn.lock
Bumps @heroku/functions-core to 0.2.6, which updates sf-fx-runtime-nodejs to 0.11.0. The primary change included in this release is https://github.com/forcedotcom/sf-fx-runtime-nodejs/pull/294, which improves error messaging for function local development.
[GUS-W-10728741](https://gus.my.salesforce.com/a07EE00000qUu23YAC)
=> fix: update functions-core to 0.2.6

command-snapshot.json, messages/env.compute.collaborator.add.md, src/commands/env/compute/collaborator/add.ts, test/commands/env/compute/collaborator/add.test.ts, yarn.lock
This PR is the updated version of [this PR](https://github.com/salesforcecli/plugin-functions/pull/364). See back to old PR for previous conversation notes.
Adds a heroku user to the the functions via cli. This enables users to use any of their compute environments
with heroku addons.
1. Pull down the PR branch
2. Enable the feature flag `heroku sudo labs:enable allow-functions-collab --user username@heroku.com`
2. Make sure that you have your scratch org, dev hub, compute environments all setup
3. Attach the compute environment to one of your databases locally by running this command from within the branch directory `sf env compute collaborator add --heroku-user:HEROKU_USER`
4. Check to see if you received an email like this
5. Try and add yourself again and see if you get this error …
=> feat: Add sf create compute collaborator add command cla missing fixed

package.json, src/commands/generate/function.ts, src/commands/run/function.ts, src/commands/run/function/start.ts, src/commands/run/function/start/container.ts, src/commands/run/function/start/local.ts, test/commands/generate/function.test.ts, test/commands/run/function.test.ts, test/commands/run/function/start.test.ts, test/commands/run/function/start/container.test.ts, yarn.lock
Updates `@salesforce/functions-core` to 0.2.8. Which includes some function template updates: https://github.com/heroku/sf-functions-core/pull/46 and https://github.com/heroku/sf-functions-core/pull/43.
[@W-10728914@](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07EE00000qVqIwYAK)
=> fix: update functions templates with functions-core 0.2.8

.circleci/config.yml
Removes the test-ts-update CI job. 
We can address typescript changes when we update the dependency.
=> chore: rm test-ts-update CI job

messages/generate.function.md
Makes the example function name `myfunction` rather than `MyFunction`.
Before:
`sf generate function --function-name MyFunction --language javascript`
After:
`sf generate function --function-name myfunction --language javascript`
```
./bin/dev generate function --help
```
@W-000@
=> docs: lower case the example function name in help message for `generate function`

.circleci/config.yml
fix dependabot-automerge job to use squash not merge which is blocked on this repo
W-X
=> ci: fix dependabot-automerge job

package.json
v1.10.0 is missing in the commit history
@W-0@
=> chore(release): 1.10.0 [ci skip]

package.json
The core plugin-env plugin also contains an "env create" subtopic, so we need to make the descriptions of the two the same.  I'm changing the description in this plugin to be more general.
@W-11241703@
=> fix: generalize the description of the "env create" topic

src/commands/env/delete.ts, src/commands/env/log/tail.ts, src/commands/env/logdrain/add.ts, src/commands/env/logdrain/list.ts, src/commands/env/logdrain/remove.ts, src/commands/env/var/get.ts, src/commands/env/var/list.ts, src/commands/env/var/set.ts, src/commands/env/var/unset.ts
[@W-10989984@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000usBW5YAM/view) [sf-cli] bug: commands indicate the wrong argument flag
Update help text for --target-compute. 
Has:
`-c, --target-compute`
Should be:
`-e, --target-compute`
Fix for:
Example output:
```
╭─scope@scope-ltmcxql ~/projects/plugin-functions ‹zw/add-json-sf-env-var-set●›
╰─$ ./bin/run env var set                                   141 ↵
›  Error: Missing required flag:
›      -c, --target-compute TARGET-COMPUTE Environment name.
›     See more help with --help
```
Does not match the help output:
```
╭─scope@scope-ltmcxql ~/projects/plugin-functions ‹zw/add-json-sf-env-var-set●›
╰─$ sf env var set --help                                   141 ↵
Set a single config value for an environment.
USAGE
$ sf …
```
=> fix: commands indicate the wrong argument flag in error msg

package.json, src/commands/env/create/compute.ts, src/commands/login/functions.ts, src/commands/login/functions/jwt.ts, src/commands/logout/functions.ts, src/hooks/deploy.ts, src/hooks/envDisplay.ts, src/hooks/envList.ts, src/lib/base.ts, src/lib/utils.ts, test/commands/env/create/compute.test.ts, test/commands/env/delete.test.ts, test/commands/login/functions.test.ts, test/commands/login/functions/jwt.test.ts, test/commands/logout/functions.test.ts, test/commands/run/function.test.ts, test/helpers/auth.ts
Use `StateAggregator` instead of `GlobalInfo`
`GlobalInfo` is being deprecated because it is highly susceptible to data loss and/or collisions since it uses a single json file for all state across all processes. `StateAggregator` splits all individual bits of state into individual files so that there's a much smaller chance of data loss when multiple commands are running concurrently. 
For reference: https://github.com/forcedotcom/sfdx-core/pull/587
@W-11214501@
=> feat: use StateAggregator

src/commands/env/create/compute.ts, test/commands/env/create/compute.test.ts
Rename references in CLI for SfFunctionsConnection to FunctionConnection
[@@W-9559660@@](https://gus.lightning.force.com/lightning/r/a07AH000000QOqcYAG/view)
=> refactor: rename SfFunctionsConnection to FunctionConnection

package.json, yarn.lock
Bumps @hk/functions-core to 0.3.2
* updates sf-fx-runtime-nodejs to 0.11.2
* The primary change included in this release is https://github.com/forcedotcom/sf-fx-runtime-nodejs/pull/357
[W-11388878](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07EE000010lxrzYAA)
@W-11388878@
=> fix: update function-core to 0.3.2

src/commands/env/var/set.ts, test/commands/env/var/unset.test.ts
refactor convoluted error handling in env var set
@W-000000@
=> refactor: env var set error handling

CHANGELOG.md, package.json
A cherry-pick of fd064b2b648a82fd150847f3dbb01c7e2e415620 to fix failing CI due to the previous release commit not having made it back to `main`.
See:
https://github.com/salesforcecli/plugin-functions/pull/481#issuecomment-1232788881
GUS-W-11739370.
=> Backport 1.13.6 release commit to `main`

package.json
This repository currently uses Yarn v1, however since no Yarn version is defined, if I run newer `yarn` locally it auto-migrates the repository to Yarn v3's new style lockfile and configuration.
Until such time as this project is migrated officially (which likely depends on Dependabot supporting Yarn 2/3), the Yarn v1 should be specified explicitly in `package.json`.
[GUS-W-11740116](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000016IKYzYAO/view).
=> chore: explicitly set yarn v1 as the packageManager

package.json, yarn.lock
Bumps @heroku/sf-functions-core to 0.4.1, which includes the following changes:
- https://github.com/heroku/sf-functions-core/pull/110
- https://github.com/heroku/sf-functions-core/pull/106
- https://github.com/heroku/sf-functions-core/pull/107
- https://github.com/heroku/sf-functions-core/pull/108
[W-11543492](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07EE000013CyjtYAC)
=> fix: bump sf-functions-core to 0.4.1

.github/workflows/manualRelease.yml
Switches the manual release github action to use a new bot user.
[@W-11955892@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000019iAa6YAE/view)
=> chore: switch bot user

package.json, yarn.lock
Bumps `@heroku/functions-core` to `0.4.2` which includes the following changes:
- https://github.com/heroku/sf-functions-core/pull/120
- https://github.com/heroku/sf-functions-core/pull/127
[@W-11854649@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000017vi0fYAA/view)
=> fix: bump functions-core to 0.4.3

src/commands/run/function/start/container.ts
exit 1 on `sf run function start container`
A request from slack. To show the command did not succeed and to be a bit clearer there is a failure.
Original WI [@W-12514513@](https://gus.lightning.force.com/a07EE00001KunfCYAR)
=> fix: exit 1 on sf run function start container

.eslintrc.js, package.json, yarn.lock
Fixes:
```
error eslint-plugin-jsdoc@39.9.1: The engine "node" is incompatible with this module. Expected version "^14 || ^16 || ^17 || ^18 || ^19". Got "20.5.0"
````
@W-14071482@
=> fix(dep): bump eslint-plugin-jsdoc from ^39.9.1 to ^43.0.5

src/commands/env/create/compute.ts, test/commands/env/create/compute.test.ts
Currently unable to diagnose customer issue SEV1 that is repeating the `await pollForResult` block in `compute.ts:75`
Customer Investigation:
[@W-14371436@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001dByE3YAK/view)
after plugins:link on this branch:
```
env 'DEBUG=*' sf env create compute --connected-org=evergreen-canary-***@salesforce.com --alias=gs0wolf1
...
sf:connection DEBUG request: {"method":"GET","url":"https://hk-fn-**orgname**gs0.my.salesforce.com/services/data/v59.0/query?q=SELECT%0A%20%20%20%20%20%20%20%20%20%20Id%2C%0A%20%20%20%20%20%20%20%20%20%20Status%2C%0A%20%20%20%20%20%20%20%20%20%20Error%0A%20%20%20%20%20%20%20%20%20%20FROM%20FunctionConnection","headers":{"content-type":"application/json","user-agent":"sfdx toolbelt:"}} +716ms
env:create:compute …
```
=> fix(compute): add more logging around start of sf env create compute

.gitignore, package.json
Publish `npm-shrinkwrap.json`
@W-15103413@
=> feat: publish npm-shrinkwrap.json
